trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Npm@1
    displayName: 'Install newman locally'
    inputs:
      command: 'custom'
      verbose: true
      customCommand: 'install newman'

  - bash: |
      npx newman \
        run "Spotify automated.postman_collection.json" \
        -e SpotifyApi.postman_environment.json -d PostmanDemoData.csv \
        --global-var spotifyClientId=$SPOTIFY_CLIENT_ID \
        --global-var spotifyClientSecret=$SPOTIFY_CLIENT_SECRET \
        -r cli,emojitrain,junit --reporter-junit-export=postman-junit-testreport.xml
    displayName: 'Execute Postman tests'
    env:
      SPOTIFY_CLIENT_ID: $(spotifyClientId)
      SPOTIFY_CLIENT_SECRET: $(spotifyClientSecret)

  - task: PublishTestResults@2
    displayName: 'Publish test results to ADO pipeline'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/postman-junit-testreport.xml'
      testRunTitle: 'Postman Tests'
